
spring:
  #config:
  #  activate:
  #    on-profile: local
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false # DBCP ??? ?? false? ??
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true

  # SQL ??? ?????? ?? ??
  sql:
    init:
      mode: always # never, always

  # H2 DBMS DataSource Connection Pool ??
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging.level:
  org.hibernate:
    type.descriptor.sql: DEBUG

server:
  tomcat:
    threads:
      max: 512          # default 200
      min-spare: 10     # default 10
    accept-count: 100   # default 100
  port: 8080